### ISSUE TITLE
[BUG] EuroLinux9 uses kernel 4.18 from EuroLinux8

### ISSUE THREAD

**Issue by Jeffrey-de-Bruijn** [EuroLinux/containers-rfc#9] opened 2022-08-03 14:26 UTC
**Describe the bug**
Wrong kernel is used in eurolinux9 container image

**Image versoin**
eurolinux/eurolinux-9:latest

**Dockerfile**
```
irrelevant
```
**To Reproduce**
```
cat /etc/os-release 
NAME="EuroLinux"
VERSION="9.0 (Sarajevo)"
ID="eurolinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="9.0"
PLATFORM_ID="platform:el9"
PRETTY_NAME="EuroLinux 9.0 (Sarajevo)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:eurolinux:eurolinux:9"
HOME_URL="https://www.euro-linux.com/"
DOCUMENTATION_URL="https://docs.euro-linux.com"
BUG_REPORT_URL="https://github.com/EuroLinux/eurolinux-distro-bugs-and-rfc/"
# We keep it for build scripts only
REDHAT_SUPPORT_PRODUCT="EuroLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9"

uname -r
4.18.0-372.13.1.el8_6.x86_64
```

**Expected behavior**
Kernel should be 5.14

**Comment by AlexBaranowski** [comment] 2022-08-03 14:46
Hi Jeffrey,

Thanks for the bug report!

The EuroLinux container image does not include the kernel package as it's not necessary for containers to have one. `uname -r` reports actually Your host machine kernel.

### Example on my computer:

```bash
[Alex@SpaceShipEL8 tmp]$ uname -r
5.18.14-1.el8.elrepo.x86_64
[Alex@SpaceShipEL8 tmp]$ podman run -it eurolinux-9:latest
[root@c4823045d675 /]# uname -r
5.18.14-1.el8.elrepo.x86_64
[root@c4823045d675 /]# 
exit
[Alex@SpaceShipEL8 tmp]$ podman run -it ubuntu:latest
root@1d20cba700aa:/# uname -r
5.18.14-1.el8.elrepo.x86_64
root@1d20cba700aa:/# 
exit
```

### Explanation:


`uname` program uses `uname`  (`man 2 uname`) system call that is asking running kernel about its name and information.

**I'm closing this one as not a bug.**

**Closed as completed by AlexBaranowski** 2022-08-03 14:46 UTC
Labels: not-a-bug
